### ISSUE TITLE
LD filtering advice

### ISSUE THREAD

**Issue by jradrion** [popgensims/analysis#36] opened 2019-07-09 21:39 UTC
I have questions for the group about some of the results from my most recent attempt to exclude tightly linked from SFS-based analyses, specifically with the hope of improving the results from stairwayplot.

The current approach I am using tends to, at least in some cases, disproportionately reduce the counts for a single intermediate allele frequency bin  (bin 4 in the example below; arabidopsis chr1).
![chr1 trees sfs](https://user-images.githubusercontent.com/20053488/60922957-c2291100-a252-11e9-9080-551296b89f6e.png)

This has the affect of smoothing the SFS for highly erratic examples, such as human chr22 (below), yet I don't have the intuition for what it going on again with the seemingly disproportionate reduction in bin 4.
![chr22 trees sfs](https://user-images.githubusercontent.com/20053488/60923133-1af8a980-a253-11e9-86df-3e92857a076b.png)

I should also mention that this effect does not seem quite as dramatic for higher sample sizes, such as n=40 for human chr22 (below), although that could just be my imagination.
![chr22 trees sfs2](https://user-images.githubusercontent.com/20053488/60923378-a4a87700-a253-11e9-88af-8c9fac02f710.png)

The whole idea behind using LD-filtering was to tame erratic SFS, where we hypothesized that the spikes might be contributing to the poor fit of stairwayplot. However, it seems like we might be introducing new biases into the SFS, which is presumably not doing much to help stairwayplot. 

The complete code for my LD-filtering can be found in /popgensims/analysis/n_t/simulations.py, but the main function is shown below:

```
def unlinked(ts,thresh,num_threads):
    mask=np.zeros(ts.num_sites,dtype="bool")

    def thread_worker(thread_index):
        ld = msp.LdCalculator(ts)
        chunk_size = int(math.ceil(len(mask) / num_threads))
        nextSite = thread_index * chunk_size
        stop = nextSite + chunk_size
        while True:
            mask[nextSite] = True
            r2 = (ld.r2_array(nextSite) <= thresh)
            if nextSite > stop or len(r2) == 0 or not np.any(r2):
                break
            nextSite += (1 + np.argmax(r2))

    threads = [
            `threading.Thread(target=thread_worker,` args=(j,))
            for j in range(num_threads)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    return mask
```

This code should be retaining a single SNP (the leftmost) for each haplotype block with pairwise r^2 > the threshold (in most cases, 0.1). 

Any thoughts or advice would be appreciated.

**Comment by petrelharp** [comment] 2019-07-10 17:08
We thought to double-check things with a SLiM simulation. Here's some code that pulls the recombination map from msprime and runs a SLiM simulation using it:
```
import os
import tempfile
from stdpopsim import homo_sapiens

def slim_script(script, name, seed):
    logfile = "{}.{}.log".format(name, seed)
    call = ("echo '" + script + "' | slim -s " + str(seed)
            + " > " + logfile + " 2>&1")
    out = os.system(call)
    if out != 0:
        print("An error occurred.")
    return out, logfile

gm = homo_sapiens.genome.chromosomes['chr22'].recombination_map()

positions = gm.get_positions()
rates = gm.get_rates()

with tempfile.TemporaryDirectory(dir=".") as tempdir:
    posfile = os.path.join(tempdir, "positions")
    with open(posfile, 'w') as f:
        for p in positions:
            f.write("{}\n".format(int(p)))
    ratefile = os.path.join(tempdir, "rates")
    with open(ratefile, 'w') as f:
        for r in rates:
            f.write("{}\n".format(r))

    recipe = """
    initialize() {{
            initializeMutationRate({mutrate});
            initializeMutationType("m1", 0.5, "f", 0.0);
            initializeGenomicElementType("g1", m1, 1.0);
            initializeGenomicElement(g1, 0, {length});
            
            // 1000 random recombination regions
            ends = asInteger(readFile("{posfile}"));
            rates = asFloat(readFile("{ratefile}"));
            initializeRecombinationRate(rates=rates, ends=ends);
    }}
    1 {{ sim.addSubpop("p1", {popsize}); }}
    10000 {{ sim.simulationFinished(); }}
    """.format(
            mutrate=1e-8,
            length=int(gm.get_length()),
            popsize=1000,
            posfile=posfile,
            ratefile=ratefile
            )

    slim_script(recipe, "test", 23)
```

**Comment by petrelharp** [comment] 2019-07-10 17:12
Just to clarify, what we're seeing is a very stochastic SFS (maybe @jradrion could post some more replicates?) - this is what we would expect with large blocks of low recombination, but the extent of the noisiness was surprising to us, and seems like it would throw off inference substantially.

**Comment by petrelharp** [comment] 2019-07-10 17:13
But, we're trying to follow usual best practices here, so if best practice (or, standard practice?) is to not LD filter, then we should not do it. But if the practice *is* to LD filter, then: how? Clearly our first guess was not the right way.

**Comment by jradrion** [comment] 2019-07-10 17:14
Here are some additional replicates for human chr22.
![chr22 trees sfs3](https://user-images.githubusercontent.com/20053488/60989709-7da58000-a2fb-11e9-9c16-61a44e8e2f78.png)
![chr22 trees sfs4](https://user-images.githubusercontent.com/20053488/60989741-8bf39c00-a2fb-11e9-8a63-2ee31ae41f87.png)

**Comment by jradrion** [comment] 2019-07-11 00:21
It doesn't look like the recombination map itself is to blame. Here are three reps of msprime vs SLiM for human chr22. SLiM sims used @petrelharp's implementation with the human recombination map (above), and simulated with constant population size. msprime sims are still using TennessenTwoPopOutOfAfrica.

![chr22 trees sfs slim](https://user-images.githubusercontent.com/20053488/61012904-46ec5b80-a335-11e9-9c4f-d0076a30e55b.png)
![chr22 trees sfs slim](https://user-images.githubusercontent.com/20053488/61012925-5a97c200-a335-11e9-913c-b3edaad2d10e.png)
![chr22 trees sfs slim](https://user-images.githubusercontent.com/20053488/61012937-713e1900-a335-11e9-9585-1cb925d0cf9c.png)

**Comment by jradrion** [comment] 2019-07-11 00:23
msprime under equilibrium will be next to test

**Comment by jeromekelleher** [comment] 2019-07-11 07:29
Thanks very much for this @jradrion. I'm not sure what to make of these tbh. It's perfectly possible there's a bug in msprime, but I have no idea where to start looking from this. @petrelharp, @andrewkern, @dschride what are your thoughts?

**Comment by dschride** [comment] 2019-07-11 16:10
One thing that jumps out is the much higher variance across msprime reps.

Quick question about how msprime simulates under these genetic maps: what happens if we give it a map with huge chunks of missing data (e.g the first third of chr22 which is all Ns)? Are we simulating those regions with zero recombination and throwing down mutations?

**Comment by petrelharp** [comment] 2019-07-11 16:58
The first thing to do is to make an apples-to-apples comparison; above msp is using two growing pops exchanging rare migrants (which increases LD) and slim is just a single pop (and, much smaller). So I'm waiting to see @jradrion's results using msprime with the same thing as the slim model.

**Comment by jradrion** [comment] 2019-07-11 17:03
@petrelharp That is what I'm showing in the second set of msp results above.

**Comment by jradrion** [comment] 2019-07-11 17:15
@dschride Those who know better can correct me if I'm wrong, but I believe that a recombination rate of zero is assumed prior to the start of of first position in the map. The first position in the map for human chr22 is 16051347, so yes, roughly a third of the chromosome should have zero recombination.

**Comment by petrelharp** [comment] 2019-07-11 17:25
> @petrelharp That is what I'm showing in the second set of msp results above.

hah, yes, sorry.

**Comment by dschride** [comment] 2019-07-11 17:25
Is this what we are doing in the slimulations?

Obviously this region would be ignored in practice (because it is all missing data).

**Comment by petrelharp** [comment] 2019-07-11 17:31
>  I believe that a recombination rate of zero is assumed prior to the start of of first position in the map.

Oh, crap. I messed that up - the positions to msprime give the *starts* of the intervals, while SLiM wants the *ends* of the intervals. I've updated my code above to do this correctly (but, could you verify, @jradrion? - in the sims we can check if there are no recombs in the zero-recomb region)

**Comment by petrelharp** [comment] 2019-07-11 17:34
I'm also noticing a discrepancy: `homo_sapiens.genome.chromosomes['chr22'].length` is 51304566 but `homo_sapiens.genome.chromosomes['chr22'].recombination_map().get_sequence_length()` is 51229805. Which is right?

**Comment by andrewkern** [comment] 2019-07-11 17:40
I bet both are correct, but the assemblies are different... checking now.

In addition, @dschride I agree-- I think most of those data would be ignored in practice. For instance in looking at the HGDP data, the first SNP to appear on chr22 is at position 10510212

**Comment by andrewkern** [comment] 2019-07-11 17:42
looks like both should be on hg19, so 51304566 is the correct length

**Comment by dschride** [comment] 2019-07-11 17:42
Yeah, the sites are all Ns so there is nothing to map your reads to!

51304566 is the length of chr22 in hg19. Not sure where 51229805 would be coming from.

**Comment by andrewkern** [comment] 2019-07-11 17:44
seems like we should implement some masking post-simulation for the analysis side. are there canonical masks we might use? i recall something like this from 1K genomes

**Comment by petrelharp** [comment] 2019-07-11 17:45
Er, but the last entry in the map file we are using is 51229805, and according to our memory of our previous checks, the positions in the map file are *ends*.

**Comment by petrelharp** [comment] 2019-07-11 17:46
That is also how msprime's `read_hapmap()` function interprets the hapmap files.

**Comment by petrelharp** [comment] 2019-07-11 17:52
Chromosome 22 map: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC311079/figure/F1/

**Comment by petrelharp** [comment] 2019-07-11 18:03
Ok, we've gotten to the bottom of this. Contrary to what I said above...

1) In the hapmap files, the position column gives coordinates for the *start* of the window that the rate column is referring to. We checked this by dividing diff(Map) by diff(Position) and verifying that this matches the Rate column.

2) In msprime's [`read_hapmap()`](https://github.com/tskit-dev/msprime/blob/1f940bf98e3d7731c4767a119fe0e11742591a7c/msprime/simulations.py#L797) function, which we use, if the first position is not zero, then it is assumed that the portion of the chromosome from 0.0 to the first position has recombination rate 0.0.

In the case of chromosome 22, this is making a *big* zero recombination region. It seems to me and @jradrion that the only sensible thing to do is to not simulate the portion of the chromosome until the first position in the map file, rather than setting an arbitrary recombination rate of 0 there. We'd do this by shifting coordinates, since msprime requires coordinates to start at 0. This should probably be an option to `read_hapmap( )`. What do you all think?

**Comment by andrewkern** [comment] 2019-07-11 18:05
this is a good idea, but i think we should also make sure that we are masking any regions of the assembly that are N's

**Comment by dschride** [comment] 2019-07-11 18:13
Yup, that explains the huge variance in the SFS: one tree governs 1/3 of your chromosome!

**Comment by petrelharp** [comment] 2019-07-11 18:16
@jradrion will simulate with msprime again without this big zero recomb rate to verify it was the cause of this stochasticity. I'm moving the more general discussion to a new issue.

**Comment by jradrion** [comment] 2019-07-11 19:25
OK, here are some msprime sims with the zero-rate interval excluded. Looking good!

![chr22 trees sfs slim](https://user-images.githubusercontent.com/20053488/61078841-6b4c4480-a3d6-11e9-9e90-cd4b7b6706d4.png)
![chr22 trees sfs slim](https://user-images.githubusercontent.com/20053488/61078859-7b642400-a3d6-11e9-97a1-c7563b92791c.png)
![chr22 trees sfs slim](https://user-images.githubusercontent.com/20053488/61078886-89b24000-a3d6-11e9-904f-5a4fab975979.png)

**Comment by jeromekelleher** [comment] 2019-07-12 06:47
Well done all, great detective work!

**Comment by andrewkern** [comment] 2019-08-07 22:01
closing this as I think we got there

**Closed by andrewkern** 2019-08-07 22:01 UTC
